name = "RhapsodieDirect"
uuid = "0ed9b2bd-c76c-4f1a-94cb-965bde98f638"
version = "0.1.0"
authors = ["Laurence DENNEULIN <ldenneulin@montesquiou.info>"]

[deps]
AstroFITS = "34e54ef0-c5bf-48ab-9e5d-cca51f35ed77"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
InterpolationKernels = "16730964-a2ec-11e9-36fa-47a4f82bfac6"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearInterpolators = "2fc109c4-9d77-11e9-32ff-e5c650334c16"
TwoDimensional = "1907e7ba-7586-4310-a2ba-dd01462aeb50"

[compat]
AstroFITS = "1.0.0"
